import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/lenis-provider";
import ScrollToTop from "@/components/ScrollToTop";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NxtWave AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} font-sans min-h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          <ScrollToTop /> {children}
        </LenisProvider>
      </body>
    </html>
  );
}
